### ISSUE TITLE
Get stuck in training cifar10 on pytorch 0.4.0

### ISSUE THREAD

**Issue by cxmscb** [locuslab/convex_adversarial#16]
Simply I change the mnist_model' input channel to 3 and choose the cifar10 dataset, then I get this error:

  File "/home/songcb/convex_adversarial-master/examples/trainer.py", line 22, in train_robust
    scatter_grad=scatter_grad)
  File "/home/songcb/.local/lib/python3.6/site-packages/convex_adversarial-0.2-py3.6.egg/convex_adversarial/dual.py", line 182, in robust_loss
  File "/home/songcb/.local/lib/python3.6/site-packages/convex_adversarial-0.2-py3.6.egg/convex_adversarial/dual.py", line 107, in __init__
TypeError: new() received an invalid combination of arguments - got (Tensor, int), but expected one of:
 * (torch.device device)
 * (tuple of ints size, torch.device device)
      didn't match because some of the arguments have invalid types: (Tensor, int)
 * (torch.Storage storage)
 * (Tensor other)
 * (object data, torch.device device)
      didn't match because some of the arguments have invalid types: (Tensor, int)

**Comment by riceric22** [comment]
This is a compatiability issue with PyTorch 0.4 0-dim tensors not playing nicely with PyTorch 0.2 code. From the trace, it looks like you're running v0.2 of the repository which works only with PyTorch 0.2, and it runs into this error because you're running it in PyTorch 0.4 which returns 0-dim tensors instead of scalars. 

Either downgrade to PyTorch 0.2 if you wish to use the repo frozen at v0.2 for our first paper, or use the master branch which I've already ported to PyTorch 0.4.

**Comment by cxmscb** [comment]
Thanks for replying!
