### ISSUE TITLE
GPU Out of memory when switching from regular to robust training

### ISSUE THREAD

**Issue by stefanwebb** [locuslab/convex_adversarial#17]
I'm trying to modify the MNIST example to start robust training after 100 epochs of training on the regular loss. I modify the training objective selection in `examples/mnist.py` so that it changes to use the robust objective after a number of epochs. However, it then terminates with a CUDA out of memory error... This doesn't happen if I start robust training from the 0th epoch. Is there an easy fix for this? Thanks

**Comment by riceric22** [comment]
Hey @stefanwebb, this is likely because a typically trained network has many ReLU activations that cross 0 over perturbations, which increases memory consumption. In `examples/mnist.py`, we schedule  the epsilon perturbation to start small (e.g. 0.01) and gradually increase it to the desired perturbation. 

This has two benefits: 
1) memory usage is decreased by virtue of there starting with less activations that cross 0 on smaller epsilon (e.g. memory usage starts small, and increases to the final amount, instead of starting large and decreasing to the final amount)
2) the method consistently converges 

So if you were to start robust training after 100 epochs of standard training, it would still be best to start with small epsilon and gradually schedule it upwards for minimal memory usage. This has a rather nice interpretation as well: epsilon=0 corresponds exactly to standard training, so scheduling the epsilon is effectively an interpolation between standard training and robust training. 

In the example code, the default schedule length for MNIST is 10 epochs, after which it will use the final desired epsilon.

**Comment by stefanwebb** [comment]
Thanks for the quick reply! This was a real lifesaver and solved the problem. I had been starting from epsilon 0.05 rather than 0.01...
